# 빌드 단계
FROM node:22-alpine AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사
COPY package.json package-lock.json* ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY . .

# 개발 환경 빌드
RUN npm run build:dev

# 서버 실행 포트 설정
EXPOSE 3000

# 개발 환경으로 설정
ENV NODE_ENV=development

# 빌드된 앱 실행
CMD ["npm", "run", "start:dev"]